# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/p/Desktop/Programs/C++/OOM Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/p/Desktop/Programs/C++/OOM Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/p/Desktop/Programs/C++/OOM Project/CMakeFiles" "/home/p/Desktop/Programs/C++/OOM Project//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/p/Desktop/Programs/C++/OOM Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OOM_Project

# Build rule for target.
OOM_Project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OOM_Project
.PHONY : OOM_Project

# fast build rule for target.
OOM_Project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/build
.PHONY : OOM_Project/fast

AirConditioner.o: AirConditioner.cpp.o
.PHONY : AirConditioner.o

# target to build an object file
AirConditioner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/AirConditioner.cpp.o
.PHONY : AirConditioner.cpp.o

AirConditioner.i: AirConditioner.cpp.i
.PHONY : AirConditioner.i

# target to preprocess a source file
AirConditioner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/AirConditioner.cpp.i
.PHONY : AirConditioner.cpp.i

AirConditioner.s: AirConditioner.cpp.s
.PHONY : AirConditioner.s

# target to generate assembly for a file
AirConditioner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/AirConditioner.cpp.s
.PHONY : AirConditioner.cpp.s

Compressor.o: Compressor.cpp.o
.PHONY : Compressor.o

# target to build an object file
Compressor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/Compressor.cpp.o
.PHONY : Compressor.cpp.o

Compressor.i: Compressor.cpp.i
.PHONY : Compressor.i

# target to preprocess a source file
Compressor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/Compressor.cpp.i
.PHONY : Compressor.cpp.i

Compressor.s: Compressor.cpp.s
.PHONY : Compressor.s

# target to generate assembly for a file
Compressor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/Compressor.cpp.s
.PHONY : Compressor.cpp.s

CoolingUnit.o: CoolingUnit.cpp.o
.PHONY : CoolingUnit.o

# target to build an object file
CoolingUnit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/CoolingUnit.cpp.o
.PHONY : CoolingUnit.cpp.o

CoolingUnit.i: CoolingUnit.cpp.i
.PHONY : CoolingUnit.i

# target to preprocess a source file
CoolingUnit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/CoolingUnit.cpp.i
.PHONY : CoolingUnit.cpp.i

CoolingUnit.s: CoolingUnit.cpp.s
.PHONY : CoolingUnit.s

# target to generate assembly for a file
CoolingUnit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/CoolingUnit.cpp.s
.PHONY : CoolingUnit.cpp.s

Freezer.o: Freezer.cpp.o
.PHONY : Freezer.o

# target to build an object file
Freezer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/Freezer.cpp.o
.PHONY : Freezer.cpp.o

Freezer.i: Freezer.cpp.i
.PHONY : Freezer.i

# target to preprocess a source file
Freezer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/Freezer.cpp.i
.PHONY : Freezer.cpp.i

Freezer.s: Freezer.cpp.s
.PHONY : Freezer.s

# target to generate assembly for a file
Freezer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/Freezer.cpp.s
.PHONY : Freezer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OOM_Project.dir/build.make CMakeFiles/OOM_Project.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OOM_Project"
	@echo "... AirConditioner.o"
	@echo "... AirConditioner.i"
	@echo "... AirConditioner.s"
	@echo "... Compressor.o"
	@echo "... Compressor.i"
	@echo "... Compressor.s"
	@echo "... CoolingUnit.o"
	@echo "... CoolingUnit.i"
	@echo "... CoolingUnit.s"
	@echo "... Freezer.o"
	@echo "... Freezer.i"
	@echo "... Freezer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

